---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPAuth
metadata:
  name: default
  namespace: vault-secrets-operator-system
spec:
  organizationID: {{ORG_ID}}
  projectID: {{PROJECT_ID}}
  servicePrincipal:
    secretRef: vso-demo-sp
