apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: payments-api
  namespace: uber-api-dev
spec:
  appName: {{HVS_APP_NAME}}
  destination:
    create: true
    labels:
      hvs: "true"
    name: stripe-test-secret-key
  refreshAfter: 1h
