apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: payments-api
  namespace: default
spec:
  appName: payments-api
  destination:
    create: true
    labels:
      hvs: "true"
    name: payments-api-secrets
  refreshAfter: 1h
